(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.FocusDailySummary=api;})(typeof window!=='undefined'?window:globalThis,function(){
  'use strict';
  const PROCEDURE_LABELS=Object.freeze({
    'fraction-meaning':'el significat de les fraccions',equivalence:'les fraccions equivalents',simplification:'la simplificació de fraccions','add-same-denominator':'les sumes de fraccions amb el mateix denominador','subtract-same-denominator':'les restes de fraccions amb el mateix denominador','add-different-denominator':'les sumes de fraccions amb denominadors diferents','subtract-different-denominator':'les restes de fraccions amb denominadors diferents','multiply-fractions':'la multiplicació de fraccions','divide-fractions':'la divisió de fraccions','compare-decimals':'la comparació de decimals','order-decimals':'l’ordenació de decimals','convert-representation':'la relació entre decimals, fraccions i percentatges','solve-one-step':'les equacions d’un pas','solve-two-step':'les equacions de dos passos','equation-parentheses':'les equacions amb parèntesis','read-value':'la lectura de gràfics','compare-data':'la comparació de dades','identify-trend':'la identificació de tendències','justify-conclusion':'les conclusions a partir de dades','estimate-length':'l’estimació de mesures','convert-length':'les conversions de longitud','scale-conversion':'les escales','length-multistep':'els problemes de conversió de més d’un pas','rectangle-area':'l’àrea de rectangles','rectangle-perimeter':'el perímetre de rectangles','percentage-increase':'els augments percentuals','percentage-decrease':'els descomptes percentuals',unspecified:'aquest procediment'});
  const unique=a=>[...new Set(a.filter(Boolean))];
  const label=(item,catalog)=>PROCEDURE_LABELS[item.procedureId]||catalog?.[item.skillId]?.title?.toLocaleLowerCase('ca')||'aquest procediment';
  function build(profile,session,catalog={}){
    const completed=(session?.items||[]).filter(i=>i.completed),autonomous=completed.filter(i=>i.correct&&i.assistance==='none'),assisted=completed.filter(i=>i.assistance&&i.assistance!=='none'),difficulty=completed.filter(i=>i.outcome==='incorrect'||i.outcome==='unknown'||i.solutionViewed),worked=unique(completed.map(i=>catalog[i.skillId]?.title)),newProcedures=unique(completed.filter(i=>i.learning?.completedAt).map(i=>label(i,catalog))),reinforced=unique(completed.filter(i=>['reinforcement','verification','prerequisite-reinforcement','return-to-procedure'].includes(i.phase)).map(i=>label(i,catalog))),prerequisites=(profile.prerequisiteReviews||[]).filter(r=>r.sessionId===session?.id),mastered=unique(completed.filter(i=>i.masteryConfirmed).map(i=>label(i,catalog))),raised=unique(completed.filter(i=>Number(i.estimatedLevelAfter)>Number(i.estimatedLevelBefore)).map(i=>catalog[i.skillId]?.title)),lowered=unique(completed.filter(i=>Number(i.estimatedLevelAfter)<Number(i.estimatedLevelBefore)).map(i=>catalog[i.skillId]?.title));
    const good=unique(autonomous.map(i=>label(i,catalog))),support=unique([...assisted,...difficulty].map(i=>label(i,catalog)));
    const adjustment=[];if(raised.length)adjustment.push(`La dificultat de ${raised.join(', ')} augmentarà progressivament perquè els resultats autònoms han estat consistents.`);if(lowered.length)adjustment.push(`Practicarem ${lowered.join(', ')} amb passos més accessibles abans de tornar a augmentar la dificultat.`);if(!adjustment.length)adjustment.push(completed.length?'Encara recollim evidències; la dificultat es manté mentre confirmem què és estable.':'La sessió encara no aporta prou evidència per ajustar la dificultat.');
    const continuing=unique([...support,...prerequisites.filter(r=>r.result==='needs-reinforcement'||!r.resolvedAt).map(r=>catalog[r.prerequisiteSkillId]?.title?.toLocaleLowerCase('ca'))]);
    return {partial:session?.status!=='completed',completedCount:completed.length,totalCount:session?.items?.length||0,worked,autonomousCount:autonomous.length,assistedCount:assisted.length,newProcedures,reinforced,good,support,prerequisites,mastered,adjustment,continuing};
  }
  function list(items,empty){return items.length?`<ul>${items.map(x=>`<li>${x}</li>`).join('')}</ul>`:`<p class="note">${empty}</p>`;}
  function render(model){const prerequisiteMessages=model.prerequisites.map(r=>r.result==='passed'?`Hem comprovat ${r.prerequisiteSkillId} i pots reprendre el procediment original.`:r.result==='needs-reinforcement'?`Continuarem reforçant ${r.prerequisiteSkillId} abans de reprendre el procediment original.`:`La comprovació de ${r.prerequisiteSkillId} queda pendent.`);return `<p class="summary-context">${model.partial?'Resum provisional':'Resum de la sessió'} · ${model.completedCount} de ${model.totalCount} activitats completades</p><div class="summary-grid"><section><h2>Què he treballat?</h2>${list(model.worked,'Encara no has completat cap activitat.')}${model.newProcedures.length?`<p><strong>Procediments nous:</strong> ${model.newProcedures.join(', ')}.</p>`:''}${model.reinforced.length?`<p><strong>Procediments reforçats:</strong> ${model.reinforced.join(', ')}.</p>`:''}</section><section><h2>Què m’ha sortit bé?</h2><p>${model.autonomousCount} activitats resoltes amb autonomia.</p>${list(model.good,'Encara no hi ha prou treball autònom per destacar un procediment.')}${model.mastered.length?`<p><strong>Domini confirmat:</strong> ${model.mastered.join(', ')}.</p>`:''}</section><section><h2>Què continuaré treballant?</h2><p>${model.assistedCount} activitats resoltes o revisades amb ajuda.</p>${list(model.continuing,'No s’ha detectat cap necessitat específica; continuarem amb pràctica variada.')}${list(prerequisiteMessages,'No ha calgut revisar prerequisits.')}</section><section><h2>Què ha ajustat FocusQuiz?</h2>${list(model.adjustment,'Encara no hi ha cap ajust.')}</section></div>`;}
  return {PROCEDURE_LABELS,build,render};
});
