(function(){
  'use strict';
  const $=s=>document.querySelector(s),skill=$('#previewSkill'),procedure=$('#previewProcedure'),format=$('#previewFormat'),level=$('#previewLevel'),mode=$('#previewMode'),attempt=$('#previewAttempt'),helpState=$('#previewHelpState');
  const available=Object.values(FocusDaily.CATALOG).filter(s=>s.generator.module==='daily');
  available.forEach(s=>skill.add(new Option(s.title,s.id)));
  function sourceFor(s){return FocusDailyActivities[s.generator.activity];}
  function lessonIds(){return Object.entries(FocusDailyLessons.lessons).filter(([,l])=>l.skillId===skill.value).map(([id])=>id);}
  function sync(){const s=FocusDaily.CATALOG[skill.value];format.replaceChildren(...s.exerciseModel.formats.map(id=>new Option(id,id)));procedure.replaceChildren(...lessonIds().map(id=>new Option(FocusDailyLessons.lessons[id].objective,id)));render();}
  function activity(){const s=FocusDaily.CATALOG[skill.value];return sourceFor(s)(Number(level.value),{...(s.generator.options||{}),formatFamily:format.value});}
  function showLesson(guided){const id=procedure.value,lesson=FocusDailyLessons.lessons[id];if(!lesson){$('#previewQuestion').innerHTML='<p>No hi ha una microlliçó específica per a aquesta combinació.</p>';return;}$('#previewMeta').textContent=`${id} · ${guided?'exemple guiat':'explicació i comprovació'}`;$('#previewQuestion').innerHTML=guided?`<p class="kicker">Exemple guiat</p><h2>${lesson.objective}</h2><p>${lesson.guided.text}</p>`:`<p class="kicker">Aprèn</p><h2>${lesson.objective}</h2><p>${lesson.explanation}</p>${lesson.visual||''}<ol class="math-steps">${lesson.steps.map(x=>`<li>${x}</li>`).join('')}</ol><p><strong>Comprovació:</strong> ${lesson.check.text}</p>`;const task=guided?lesson.guided:lesson.check;$('#previewChoices').innerHTML=task.choices.map(x=>`<button type="button" class="answer-option">${x}</button>`).join('');$('#previewHelp').hidden=false;$('#previewHelp').innerHTML=`<strong>Resposta de desenvolupament:</strong> ${task.answer}`;}
  function showAttempt(q){const state=attempt.value,hints=q.hints||[q.explanation,'Comprova cada pas abans de continuar.'];$('#previewFeedback').innerHTML=state==='specific-error'?'<strong>Encara no.</strong> Revisa si has intercanviat termes o unitats. Conservem la primera resposta.':state==='generic-error'?'<strong>Encara no.</strong> Revisa el procediment amb la primera pista.':state==='second-attempt'?'<strong>Segon intent.</strong> La primera resposta continua desada i aquest intent és assistit.':state==='solution'?`<strong>Solució revisada.</strong> ${q.explanation||''}`:state==='verification'?'<strong>Comprovació autònoma.</strong> Mateix procediment, dades noves i cap ajuda activa.':'';const help={none:'',hint1:hints[0],hint2:hints[1]||q.explanation,solution:`Resposta: ${q.answer}. ${q.explanation||''}`}[helpState.value];$('#previewHelp').hidden=!help;$('#previewHelp').textContent=help;}
  function showPrerequisite(q){const cognitive=FocusDaily.describeFormat(q,q.type),dependency=FocusDailyPrerequisites.DEPENDENCIES[cognitive.procedure]?.[0];$('#previewMeta').textContent=`Prerequisit possible de ${cognitive.procedure}`;$('#previewQuestion').innerHTML=dependency?`<p class="kicker">Comprovació breu de prerequisit</p><h2>${FocusDaily.CATALOG[dependency.skillId].title}</h2><p>${dependency.reason}</p><p>Només s’activaria després d’errors repetits compatibles o dependència sistemàtica de pistes.</p>`:'<p>Aquest procediment no té un prerequisit comprovable definit dins del banc actual.</p>';$('#previewFeedback').textContent='Superar-la retorna al procediment original; necessitar reforç no rebaixa automàticament tota l’habilitat.';}
  function showSummary(){const p=FocusDaily.createProfile('preview'),s={id:'preview',status:attempt.value==='fresh'?'in-progress':'completed',items:[{completed:true,skillId:skill.value,procedureId:'compare-decimals',correct:true,outcome:'correct',assistance:'none',estimatedLevelBefore:1,estimatedLevelAfter:1},{completed:true,skillId:skill.value,procedureId:'order-decimals',correct:true,outcome:'correct',assistance:'hint',learning:{completedAt:'preview'}}]};$('#previewQuestion').innerHTML=FocusDailySummary.render(FocusDailySummary.build(p,s,FocusDaily.CATALOG));$('#previewMeta').textContent='Resum pedagògic amb dades fictícies; no s’ha consultat cap perfil.';}
  function render(){const q=$('#previewQuestion'),choices=$('#previewChoices'),feedback=$('#previewFeedback'),help=$('#previewHelp');q.innerHTML='';choices.innerHTML='';feedback.textContent='';help.textContent='';help.hidden=true;if(mode.value==='lesson'||mode.value==='guided')return showLesson(mode.value==='guided');if(mode.value==='summary')return showSummary();const exercise=activity();$('#previewMeta').textContent=`${skill.value} · ${exercise.formatId} · dificultat real ${exercise.actualDifficulty||exercise.difficulty}`;q.innerHTML=`${exercise.html||''}<div>${exercise.text}</div>`;choices.innerHTML=(exercise.choices||[]).map(x=>`<button type="button" class="answer-option">${x}</button>`).join('');if(mode.value==='prerequisite')return showPrerequisite(exercise);if(mode.value==='attempt')showAttempt(exercise);else{$('#previewHelp').hidden=false;$('#previewHelp').innerHTML=`${(exercise.hints||[]).map((x,i)=>`<p><strong>Pista ${i+1}:</strong> ${x}</p>`).join('')}<p><strong>Solució:</strong> ${exercise.answer}. ${exercise.explanation||''}</p>`;}}
  skill.onchange=sync;[procedure,format,level,mode,attempt,helpState].forEach(x=>x.onchange=render);$('#previewWidth').onchange=e=>$('#previewViewport').classList.toggle('preview-mobile',e.target.value==='mobile');$('#previewNew').onclick=render;sync();
})();
