(function(){
  'use strict';
  const definitions={decimals:['compare','order','representation','application','increase','tax'],fractions:['sharing','recipe','compare-context','scale'],equations:['calculation','complete','error-detection','reasoning'],data:['visual','compare','reasoning','table','trend'],units:['calculation','application','estimate','time','capacity'],geometry:['visual','application','error-detection','estimate']};
  const lessonByActivity={fractions:'fraction-add-sub',equations:'linear-equation',decimals:'percent-change',geometry:'geometry-area-perimeter',data:'graph-reading',units:'unit-conversion'};
  const activity=document.querySelector('#previewActivity'),format=document.querySelector('#previewFormat'),level=document.querySelector('#previewLevel'),mode=document.querySelector('#previewMode');Object.keys(definitions).forEach(id=>activity.add(new Option(id,id)));
  function formats(){format.replaceChildren(...definitions[activity.value].map(id=>new Option(id,id)));render();}
  function render(){const question=document.querySelector('#previewQuestion'),choices=document.querySelector('#previewChoices'),help=document.querySelector('#previewHelp'),lesson=FocusDailyLessons.lessons[lessonByActivity[activity.value]];if(mode.value==='lesson'||mode.value==='guided'){document.querySelector('#previewMeta').textContent=`${lessonByActivity[activity.value]} · ${mode.value==='lesson'?'microlliçó':'exemple guiat'}`;question.innerHTML=mode.value==='lesson'?`<h2>${lesson.objective}</h2><p>${lesson.explanation}</p>${lesson.visual||''}<ol class="math-steps">${lesson.steps.map(s=>`<li>${s}</li>`).join('')}</ol>`:`<h2>Exemple guiat</h2><p>${lesson.guided.text}</p>`;choices.innerHTML=(mode.value==='guided'?lesson.guided.choices:lesson.check.choices).map(c=>`<button class="answer-option" type="button">${c}</button>`).join('');help.innerHTML=`<p><strong>Resposta:</strong> ${mode.value==='guided'?lesson.guided.answer:lesson.check.answer}</p>`;return;}const q=FocusDailyActivities[activity.value](Number(level.value),{formatFamily:format.value});document.querySelector('#previewMeta').textContent=`${q.templateId||q.formatId} · format ${q.formatId} · dificultat real ${q.actualDifficulty||q.difficulty}`;question.innerHTML=`${q.html||''}<div>${q.text}</div>`;choices.innerHTML=(q.choices||[]).map(c=>`<button class="answer-option" type="button">${c}</button>`).join('');help.innerHTML=mode.value==='feedback'?`<p><strong>Primer intent:</strong> Conservem la resposta i oferim una pista específica sense atribuir una causa no demostrada.</p><p><strong>Segon intent:</strong> ${q.explanation}</p><p><strong>Comprovació posterior:</strong> una activitat semblant però diferent.</p>`:`${(q.hints||[]).map((h,i)=>`<p><strong>Pista ${i+1}:</strong> ${h}</p>`).join('')}<p><strong>Resposta:</strong> ${q.answer}</p><p><strong>Explicació:</strong> ${q.explanation||''}</p>`;}
  activity.onchange=formats;format.onchange=render;level.onchange=render;mode.onchange=render;document.querySelector('#previewNew').onclick=render;formats();
})();
