(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;root.FocusDailyLessons=api;})(typeof window!=='undefined'?window:globalThis,function(){
  'use strict';
  const frac=(a,b)=>`<span class="math-frac"><span class="math-frac__num">${a}</span><span class="math-frac__bar"></span><span class="math-frac__den">${b}</span></span>`;
  const lessons={
    'fraction-meaning':{skillId:'fractions.concept',objective:'Interpretar una fracció com una part d’un tot.',explanation:'El denominador indica en quantes parts iguals dividim el tot; el numerador, quantes en prenem.',visual:`<div class="lesson-parts" role="img" aria-label="Tres de quatre parts marcades"><i></i><i></i><i></i><i class="empty"></i></div>`,steps:[`Hi ha 4 parts iguals: el denominador és 4.`,`N’hi ha 3 de marcades: el numerador és 3.`,`La fracció és ${frac(3,4)}.`],check:{text:'En 2/5, què indica el 5?',choices:['Les parts iguals totals','Les parts triades','El resultat d’una divisió'],answer:'Les parts iguals totals'},guided:{text:'Si 4 de 6 parts estan marcades, quin és el numerador?',choices:['4','6','2'],answer:'4'}},
    'fraction-equivalence':{skillId:'fractions.equivalence',objective:'Construir fraccions equivalents.',explanation:'Multipliquem o dividim numerador i denominador pel mateix nombre; el valor no canvia.',visual:`<p class="lesson-equation">${frac(1,2)} = ${frac(2,4)}</p>`,steps:['De 1 a 2 multipliquem per 2.','També multipliquem 2 per 2 i obtenim 4.','Hem canviat l’escriptura, no la quantitat.'],check:{text:'Per completar 2/3 = 8/?, quin factor usem?',choices:['4','6','3'],answer:'4'},guided:{text:'Completa el denominador: 2/3 = 8/?',choices:['12','11','24'],answer:'12'}},
    'fraction-simplify':{skillId:'fractions.simplification',objective:'Simplificar fins a una fracció irreductible.',explanation:'Dividim els dos termes per un divisor comú.',visual:`<p class="lesson-equation">${frac(12,18)} → ${frac(2,3)}</p>`,steps:['12 i 18 són divisibles per 6.','12 ÷ 6 = 2 i 18 ÷ 6 = 3.','2 i 3 ja no tenen divisor comú.'],check:{text:'Quina operació fem als dos termes?',choices:['Dividir pel mateix nombre','Restar el mateix nombre','Intercanviar-los'],answer:'Dividir pel mateix nombre'},guided:{text:'Simplifica 8/12 dividint per 4. Quin numerador queda?',choices:['2','3','4'],answer:'2'}},
    'fraction-add-sub':{skillId:'fractions.operations',objective:'Sumar o restar fraccions.',explanation:'Necessitem un denominador comú abans d’operar els numeradors.',visual:`<p class="lesson-equation">${frac(1,2)} + ${frac(1,3)} = ${frac(3,6)} + ${frac(2,6)}</p>`,steps:['Busquem el denominador comú 6.','Transformem 1/2 en 3/6 i 1/3 en 2/6.','Sumem: 3/6 + 2/6 = 5/6.'],check:{text:'Què cal igualar abans de sumar?',choices:['Els denominadors','Els numeradors','Els resultats'],answer:'Els denominadors'},guided:{text:'1/4 + 2/4: quin numerador obtenim?',choices:['3','4','8'],answer:'3'}},
    'fraction-multiply-divide':{skillId:'fractions.operations',objective:'Multiplicar i dividir fraccions.',explanation:'Per multiplicar operem en línia. Per dividir, multipliquem per la inversa de la segona fracció.',visual:`<p class="lesson-equation">${frac(2,3)} ÷ ${frac(4,5)} = ${frac(2,3)} × ${frac(5,4)}</p>`,steps:['Conservem la primera fracció.','Invertim la segona: 4/5 passa a 5/4.','Multipliquem i simplifiquem.'],check:{text:'En una divisió, quina fracció invertim?',choices:['La segona','La primera','Totes dues'],answer:'La segona'},guided:{text:'Per dividir per 3/7, per quina fracció multipliquem?',choices:['7/3','3/7','1/3'],answer:'7/3'}},
    'linear-equation':{skillId:'algebra.linear',objective:'Aïllar la incògnita mantenint la igualtat.',explanation:'Fem la mateixa operació als dos membres, desfent les operacions en ordre invers.',visual:'<p class="lesson-equation">3x + 2 = 14 → 3x = 12 → x = 4</p>',steps:['Restem 2 als dos membres.','Queda 3x = 12.','Dividim els dos membres entre 3.'],check:{text:'Què fem primer a 3x + 2 = 14?',choices:['Restar 2 als dos membres','Dividir entre 2','Sumar 3'],answer:'Restar 2 als dos membres'},guided:{text:'A 4x = 20, quin pas aïlla x?',choices:['Dividir entre 4','Restar 4','Multiplicar per 4'],answer:'Dividir entre 4'}},
    'percent-change':{skillId:'percentages.meaning',objective:'Calcular un descompte o augment.',explanation:'Calculem primer la part percentual i després la restem o la sumem al valor inicial.',visual:'<p class="lesson-equation">20% de 50 = 10 → descompte: 50 − 10 = 40</p>',steps:['20% és 0,20.','0,20 × 50 = 10.','En un descompte, restem 10.'],check:{text:'En un augment, què fem amb la part percentual?',choices:['La sumem','La restem','La ignorem'],answer:'La sumem'},guided:{text:'El 10% de 80 és...',choices:['8','10','72'],answer:'8'}},
    'geometry-area-perimeter':{skillId:'geometry.measure',objective:'Distingir àrea i perímetre.',explanation:'L’àrea mesura la superfície; el perímetre recorre el contorn.',visual:'<svg viewBox="0 0 240 130" role="img" aria-label="Rectangle de 6 per 4"><rect x="35" y="20" width="170" height="80"/><text x="120" y="122">6 cm</text><text x="5" y="65">4 cm</text></svg>',steps:['Àrea: 6 × 4 = 24 cm².','Perímetre: 6 + 4 + 6 + 4.','Perímetre = 20 cm.'],check:{text:'Quina magnitud usa unitats quadrades?',choices:['L’àrea','El perímetre','La longitud'],answer:'L’àrea'},guided:{text:'Rectangle 5 × 3: quina operació dona l’àrea?',choices:['5 × 3','5 + 3','2 × 5'],answer:'5 × 3'}},
    'graph-reading':{skillId:'data.interpretation',objective:'Llegir i comparar dades d’un gràfic.',explanation:'Primer llegim títol, etiquetes i escala; després comparem valors.',visual:'<svg viewBox="0 0 240 130" role="img" aria-label="Barres A igual a 4 i B igual a 7"><rect x="55" y="65" width="42" height="45"/><rect x="145" y="30" width="42" height="80"/><text x="76" y="126">A: 4</text><text x="166" y="126">B: 7</text></svg>',steps:['La barra A val 4.','La barra B val 7.','B supera A en 7 − 4 = 3.'],check:{text:'Què cal comprovar abans de comparar barres?',choices:['L’escala i les etiquetes','Només el color','L’ordre alfabètic'],answer:'L’escala i les etiquetes'},guided:{text:'Si A=4 i B=7, quina diferència hi ha?',choices:['3','11','7'],answer:'3'}},
    'unit-conversion':{skillId:'measurement.units',objective:'Aplicar un factor de conversió.',explanation:'Escrivim l’equivalència i multipliquem o dividim segons la direcció.',visual:'<p class="lesson-equation">1 m = 100 cm → 3 m = 300 cm</p>',steps:['Identifiquem la unitat inicial i final.','De metres a centímetres multipliquem per 100.','3 × 100 = 300.'],check:{text:'De metres a centímetres, què fem?',choices:['Multiplicar per 100','Dividir per 100','Sumar 100'],answer:'Multiplicar per 100'},guided:{text:'2 m són...',choices:['200 cm','20 cm','2.000 cm'],answer:'200 cm'}}
  };
  function procedureFor(exercise,skillId){const f=exercise.formatId||'';if(skillId==='fractions.concept')return'fraction-meaning';if(skillId==='fractions.equivalence')return'fraction-equivalence';if(skillId==='fractions.simplification')return'fraction-simplify';if(skillId==='fractions.operations')return /÷|×/.test(f)?'fraction-multiply-divide':'fraction-add-sub';if(skillId==='algebra.linear')return'linear-equation';if(skillId==='percentages.meaning'||/percent/.test(f))return'percent-change';if(skillId==='geometry.measure')return'geometry-area-perimeter';if(skillId==='data.interpretation')return'graph-reading';if(skillId==='measurement.units')return'unit-conversion';return null;}
  function shouldIntroduce(profile,skillId,lessonId,repeatedDifficulty=false){if(!lessonId)return false;const state=profile.lessons?.[lessonId],evidence=profile.skills?.[skillId]?.evidences||[];const matches=e=>lessonId==='fraction-multiply-divide'?/×|÷/.test(e.formatId||''):lessonId==='fraction-add-sub'?/\+|−/.test(e.formatId||''):true;const autonomous=evidence.some(e=>e.correct&&e.assistance==='none'&&matches(e));return repeatedDifficulty||(!state?.guidedCompleted&&!autonomous);}
  return {lessons,procedureFor,shouldIntroduce};
});
