(()=>{
const KEY='focusmind-results-v1';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const games=[
{id:'cafe-focus',name:'Bar',area:'Atenció · Memòria · Velocitat',desc:'Serveix comandes de cafeteria recordant begudes i reaccionant abans que s’acabi el temps.',diff:'Progressiva',duration:'90 s',emoji:'☕',url:'/focusmind-games/bar/bar.html'},
{id:'bar2-focus',name:'Bar2',area:'Atenció · Memòria · Velocitat',desc:'Prepara cafès i entrena l’atenció, la memòria i la precisió.',diff:'Progressiva',duration:'90 s',emoji:'☕',url:'/focusmind-games/bar2/bar2.html'},
{id:'sequencia-lluminosa',name:'Seqüència lluminosa',area:'Memòria',desc:'Plantilla preparada per bolcar-hi el teu joc de seqüència lluminosa.',diff:'Pendent',duration:'2-4 min',emoji:'✨',url:'/focusmind-games/sequencia-lluminosa/sequencia-lluminosa.html'}];
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}} function write(v){localStorage.setItem(KEY,JSON.stringify(v))}
window.saveFocusMindResult=(r)=>{const item={id:crypto?.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),...r};write([item,...read()].slice(0,200));return item};
window.getFocusMindResults=read; window.getFocusMindBestScore=(n)=>Math.max(0,...read().filter(r=>r.gameName===n).map(r=>r.score||0)); window.getFocusMindAverageAccuracy=()=>avg(read().map(r=>r.accuracy)); window.getFocusMindTotalGamesPlayed=()=>read().length; window.getFocusMindRecentGames=()=>read().slice(0,10); window.getFocusMindBestArea=()=>areaSort()[0]?.[0]||'—'; window.getFocusMindWeakestArea=()=>areaSort().at(-1)?.[0]||'—';
function avg(a){a=a.filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0} function areaSort(){const m={};read().forEach(r=>{(m[r.cognitiveArea]??=[]).push(r.accuracy||0)});return Object.entries(m).map(([k,v])=>[k,avg(v)]).sort((a,b)=>b[1]-a[1])}
function bestGlobal(){return Math.max(0,...read().map(r=>r.score||0))} function avgRt(){return avg(read().map(r=>r.averageReactionTime))}
function render(){let root=$('#view-focusmind'); if(!root)return; root.dataset.ready='true'; root.className='focusmind-shell'; root.innerHTML=`<div class="fm-top"><div class="fm-brand"><div class="fm-logo">🧠</div><div><h2>FocusMind</h2><p>Entrena la teva ment</p></div></div><div class="fm-nav"><button class="fm-btn secondary" data-fm="home">Inici</button><button class="fm-btn secondary" data-fm="dashboard">Dashboard</button><button class="fm-btn secondary" data-fm="jocs">Jocs</button><button class="fm-btn secondary" data-fm="resultats">Resultats</button><button class="fm-btn" onclick="showView('home')">Tornar a FocusQuiz</button></div></div><div class="fm-view"></div>`; root.addEventListener('click',handle); if(location.pathname.startsWith('/focusmind')) route(location.pathname); else homeView()}
function nav(path){history.pushState(null,'',path);route(path)} window.addEventListener('popstate',()=>{if(location.pathname.startsWith('/focusmind')){showView('focusmind');route(location.pathname)}else if(typeof showView==='function'){showView('home')}});
function handle(e){let b=e.target.closest('[data-fm]'); if(!b)return; const v=b.dataset.fm; if(v==='home')nav('/focusmind'); else if(v==='dashboard')nav('/focusmind/dashboard'); else if(v==='jocs')nav('/focusmind/jocs'); else if(v==='resultats')nav('/focusmind/resultats'); else if(v.startsWith('play:')){const id=v.slice(5); const game=games.find(g=>g.id===id); if(game?.url) location.href=game.url; else nav('/focusmind/joc/'+id);}}
function route(p){if(typeof showView==='function')showView('focusmind'); const v=$('.fm-view'); if(!v)return; const id=(p.match(/\/focusmind\/joc\/([^/?#]+)/)||[])[1]; if(id){const game=games.find(g=>g.id===id); if(game?.url){location.href=game.url; return;} return gamesView();} if(p.includes('/jocs'))return gamesView(); if(p.includes('/resultats'))return resultsView(); if(p.includes('/dashboard'))return dashView(); homeView()}
function homeView(){ $('.fm-view').innerHTML=`<section class="fm-hero"><div class="fm-hero-card fm-glass"><div class="fm-kicker">Psicologia cognitiva aplicada</div><h1 class="fm-title">FocusMind</h1><p class="fm-lead">Un espai integrat a FocusQuiz per treballar atenció, memòria de treball, velocitat de processament i flexibilitat cognitiva amb partides curtes, tàctils i fàcils d’utilitzar en tauleta.</p><div class="fm-actions"><button class="fm-btn" data-fm="dashboard">Comença l’entrenament</button><button class="fm-btn secondary" data-fm="jocs">Veure tots els jocs</button></div><div class="fm-home-metrics"><span class="fm-mini-metric">Sessions de 30 s a 4 min</span><span class="fm-mini-metric">Resultats locals</span><span class="fm-mini-metric">Pensat per iPad</span></div><div class="fm-benefits">${['Memòria','Atenció','Velocitat','Flexibilitat mental','Percepció visual'].map(x=>`<div class="fm-chip">✦ ${x}</div>`).join('')}</div><p class="fm-fullscreen-note">Consell: activa el <strong>Mode pantalla completa</strong> del navegador per jugar millor en iPad.</p></div><div class="fm-psychology-panel fm-glass"><div class="fm-brain-lines"></div><div class="fm-face-cluster"><div class="fm-face fm-face--left"><i></i></div><div class="fm-face fm-face--main"><i></i></div><div class="fm-face fm-face--right"><i></i></div></div><h3>Entrenament mental amb mirada humana</h3><p class="fm-muted">Una estètica més psicològica i serena, connectada amb els colors suaus de FocusQuiz i preparada per a acadèmies.</p></div></section>`}
function stat(n,v){return`<div class="fm-stat fm-glass"><span class="fm-muted">${n}</span><strong>${v}</strong></div>`} function progress(){return ['Memòria','Atenció','Velocitat','Flexibilitat','Percepció visual'].map((a,i)=>`<div class="fm-progress"><b>${a}</b><div class="fm-bar"><i style="width:${Math.max(12,avg(read().filter(r=>r.cognitiveArea===a).map(r=>r.accuracy))||[72,68,64,58,62][i])}%"></i></div></div>`).join('')}
function dashView(){ $('.fm-view').innerHTML=`<h1 class="fm-section-title">Dashboard FocusMind</h1><div class="fm-stats">${stat('Partides jugades',read().length)+stat('Millor puntuació',bestGlobal())+stat('Precisió mitjana',getFocusMindAverageAccuracy()+'%')+stat('Temps mitjà',avgRt()+' ms')+stat('Àrea més forta',getFocusMindBestArea())+stat('Àrea a millorar',getFocusMindWeakestArea())}</div><div class="fm-progress-grid">${progress()}</div><div class="fm-game-grid">${cards()}</div>`}
function gamesView(){ $('.fm-view').innerHTML=`<h1 class="fm-section-title">Jocs FocusMind</h1><p class="fm-lead">Cada joc treballa una habilitat concreta i desa resultats locals per veure evolució sense necessitat de backend.</p><div class="fm-game-grid">${cards()}</div>`} function cards(){return games.map(g=>`<article class="fm-game-card fm-glass"><div class="fm-game-art">${g.image?`<img src="${g.image}" alt="" loading="lazy">`:`<span class="fm-game-emoji" aria-hidden="true">${g.emoji||'✦'}</span>`}</div><h3>${g.name}</h3><p class="fm-muted">${g.desc}</p><div class="fm-game-tags"><span>Objectiu: ${g.area}</span><span>${g.diff}</span><span>${g.duration}</span></div><p class="fm-muted"><strong>Què entrena?</strong> Precisió, autocontrol i resposta tàctil ràpida adaptada a tauleta.</p><button class="fm-btn" data-fm="play:${g.id}">Jugar</button></article>`).join('')}
function resultsView(){const rs=read(); $('.fm-view').innerHTML=`<h1 class="fm-section-title">Resultats</h1>${!rs.length?`<div class="fm-empty fm-glass">Encara no hi ha partides registrades. Comença un entrenament per veure la teva evolució.</div>`:`<div class="fm-stats">${stat('Total partides',rs.length)+stat('Millor global',bestGlobal())+stat('Millor joc',rs.sort((a,b)=>(b.score||0)-(a.score||0))[0]?.gameName||'—')+stat('Precisió mitjana',getFocusMindAverageAccuracy()+'%')+stat('Àrea forta',getFocusMindBestArea())+stat('Àrea a millorar',getFocusMindWeakestArea())}</div><div class="fm-badges">${badges().map(b=>`<div class="fm-badge">🏅 ${b}</div>`).join('')}</div><table class="fm-table"><thead><tr><th>Joc</th><th>Punts</th><th>Precisió</th><th>Data</th></tr></thead><tbody>${rs.slice(0,10).map(r=>`<tr><td>${r.gameName}</td><td>${r.score}</td><td>${r.accuracy}%</td><td>${new Date(r.date).toLocaleDateString('ca')}</td></tr>`).join('')}</tbody></table>`}`}
function badges(){const rs=read(), out=[]; if(rs.length)out.push('Primera partida'); if(rs.length>=5)out.push('5 partides jugades'); if(rs.some(r=>r.accuracy>=90))out.push('90% de precisió'); if(rs.some(r=>r.score>=1000))out.push('1000 punts'); if(rs.some(r=>r.cognitiveArea==='Memòria'&&r.score>700))out.push('Mestre de la memòria'); if(rs.some(r=>r.cognitiveArea==='Atenció'&&r.accuracy>80))out.push('Atenció activa'); return out.length?out:['Juga per desbloquejar badges']}
window.initFocusMind=render; document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.startsWith('/focusmind')){render(); if(typeof showView==='function') showView('focusmind');}});
})();
