(()=>{
const KEY='focusmind-results-v1';
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const games=[
{id:'sequencia',name:'Seqüència lluminosa',area:'Memòria',desc:'Memoritza el patró i repeteix-lo en el mateix ordre.',diff:'Progressiva',duration:'2-4 min',image:'assets/focusmind/sequencia.svg'},
{id:'diferent',name:'Troba el diferent',area:'Atenció',desc:'Localitza el símbol diferent abans que s’acabi el temps.',diff:'Mitjana',duration:'10 rondes',image:'assets/focusmind/diferent.svg'},
{id:'color-paraula',name:'Color contra paraula',area:'Atenció',desc:'Ignora la paraula. Selecciona el color real del text.',diff:'Alta',duration:'30 s',image:'assets/focusmind/color-paraula.svg'},
{id:'memoria-posicio',name:'Memòria de posició',area:'Memòria',desc:'Recorda on apareixen els punts i marca’ls després.',diff:'Progressiva',duration:'8 rondes',image:'assets/focusmind/memoria-posicio.svg'},
{id:'ordre-creixent',name:'Ordre creixent',area:'Velocitat',desc:'Prem els nombres de menor a major tan ràpid com puguis.',diff:'Mitjana',duration:'8 rondes',image:'assets/focusmind/ordre-creixent.svg'},
{id:'canvi-regla',name:'Canvi de regla',area:'Flexibilitat',desc:'Adapta la resposta a una norma que canvia constantment.',diff:'Alta',duration:'20 rondes',image:'assets/focusmind/canvi-regla.svg'},
{id:'cafe-focus',name:'Bar',area:'Atenció · Memòria · Velocitat',desc:'Serveix comandes de cafeteria recordant begudes i reaccionant abans que s’acabi el temps.',diff:'Progressiva',duration:'90 s',emoji:'☕'}];
function read(){try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}} function write(v){localStorage.setItem(KEY,JSON.stringify(v))}
window.saveFocusMindResult=(r)=>{const item={id:crypto?.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),...r};write([item,...read()].slice(0,200));return item};
window.getFocusMindResults=read; window.getFocusMindBestScore=(n)=>Math.max(0,...read().filter(r=>r.gameName===n).map(r=>r.score||0)); window.getFocusMindAverageAccuracy=()=>avg(read().map(r=>r.accuracy)); window.getFocusMindTotalGamesPlayed=()=>read().length; window.getFocusMindRecentGames=()=>read().slice(0,10); window.getFocusMindBestArea=()=>areaSort()[0]?.[0]||'—'; window.getFocusMindWeakestArea=()=>areaSort().at(-1)?.[0]||'—';
function avg(a){a=a.filter(Number.isFinite);return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0} function areaSort(){const m={};read().forEach(r=>{(m[r.cognitiveArea]??=[]).push(r.accuracy||0)});return Object.entries(m).map(([k,v])=>[k,avg(v)]).sort((a,b)=>b[1]-a[1])}
function bestGlobal(){return Math.max(0,...read().map(r=>r.score||0))} function avgRt(){return avg(read().map(r=>r.averageReactionTime))}
function render(){let root=$('#view-focusmind'); if(!root)return; root.dataset.ready='true'; root.className='focusmind-shell'; root.innerHTML=`<div class="fm-top"><div class="fm-brand"><div class="fm-logo">🧠</div><div><h2>FocusMind</h2><p>Entrena la teva ment</p></div></div><div class="fm-nav"><button class="fm-btn secondary" data-fm="home">Inici</button><button class="fm-btn secondary" data-fm="dashboard">Dashboard</button><button class="fm-btn secondary" data-fm="jocs">Jocs</button><button class="fm-btn secondary" data-fm="resultats">Resultats</button><button class="fm-btn" onclick="showView('home')">Tornar a FocusQuiz</button></div></div><div class="fm-view"></div>`; root.addEventListener('click',handle); if(location.pathname.startsWith('/focusmind')) route(location.pathname); else homeView()}
function nav(path){history.pushState(null,'',path);route(path)} window.addEventListener('popstate',()=>{if(location.pathname.startsWith('/focusmind')){showView('focusmind');route(location.pathname)}else if(typeof showView==='function'){showView('home')}});
function handle(e){let b=e.target.closest('[data-fm]'); if(!b)return; const v=b.dataset.fm; if(v==='home')nav('/focusmind'); else if(v==='dashboard')nav('/focusmind/dashboard'); else if(v==='jocs')nav('/focusmind/jocs'); else if(v==='resultats')nav('/focusmind/resultats'); else if(v.startsWith('play:')){const id=v.slice(5); if(id==='cafe-focus') location.href='cafe-focus.html'; else nav('/focusmind/joc/'+id);}}
function route(p){if(typeof showView==='function')showView('focusmind'); const v=$('.fm-view'); if(!v)return; const id=(p.match(/\/focusmind\/joc\/([^/?#]+)/)||[])[1]; if(id==='cafe-focus') { location.href='cafe-focus.html'; return; } if(id)return startGame(id); if(p.includes('/jocs'))return gamesView(); if(p.includes('/resultats'))return resultsView(); if(p.includes('/dashboard'))return dashView(); homeView()}
function homeView(){ $('.fm-view').innerHTML=`<section class="fm-hero"><div class="fm-hero-card fm-glass"><div class="fm-kicker">Psicologia cognitiva aplicada</div><h1 class="fm-title">FocusMind</h1><p class="fm-lead">Un espai integrat a FocusQuiz per treballar atenció, memòria de treball, velocitat de processament i flexibilitat cognitiva amb partides curtes, tàctils i fàcils d’utilitzar en tauleta.</p><div class="fm-actions"><button class="fm-btn" data-fm="dashboard">Comença l’entrenament</button><button class="fm-btn secondary" data-fm="jocs">Veure tots els jocs</button></div><div class="fm-home-metrics"><span class="fm-mini-metric">Sessions de 30 s a 4 min</span><span class="fm-mini-metric">Resultats locals</span><span class="fm-mini-metric">Pensat per iPad</span></div><div class="fm-benefits">${['Memòria','Atenció','Velocitat','Flexibilitat mental','Percepció visual'].map(x=>`<div class="fm-chip">✦ ${x}</div>`).join('')}</div><p class="fm-fullscreen-note">Consell: activa el <strong>Mode pantalla completa</strong> del navegador per jugar millor en iPad.</p></div><div class="fm-psychology-panel fm-glass"><div class="fm-brain-lines"></div><div class="fm-face-cluster"><div class="fm-face fm-face--left"><i></i></div><div class="fm-face fm-face--main"><i></i></div><div class="fm-face fm-face--right"><i></i></div></div><h3>Entrenament mental amb mirada humana</h3><p class="fm-muted">Una estètica més psicològica i serena, connectada amb els colors suaus de FocusQuiz i preparada per a acadèmies.</p></div></section>`}
function stat(n,v){return`<div class="fm-stat fm-glass"><span class="fm-muted">${n}</span><strong>${v}</strong></div>`} function progress(){return ['Memòria','Atenció','Velocitat','Flexibilitat','Percepció visual'].map((a,i)=>`<div class="fm-progress"><b>${a}</b><div class="fm-bar"><i style="width:${Math.max(12,avg(read().filter(r=>r.cognitiveArea===a).map(r=>r.accuracy))||[72,68,64,58,62][i])}%"></i></div></div>`).join('')}
function dashView(){ $('.fm-view').innerHTML=`<h1 class="fm-section-title">Dashboard FocusMind</h1><div class="fm-stats">${stat('Partides jugades',read().length)+stat('Millor puntuació',bestGlobal())+stat('Precisió mitjana',getFocusMindAverageAccuracy()+'%')+stat('Temps mitjà',avgRt()+' ms')+stat('Àrea més forta',getFocusMindBestArea())+stat('Àrea a millorar',getFocusMindWeakestArea())}</div><div class="fm-progress-grid">${progress()}</div><div class="fm-game-grid">${cards()}</div>`}
function gamesView(){ $('.fm-view').innerHTML=`<h1 class="fm-section-title">Jocs FocusMind</h1><p class="fm-lead">Cada joc treballa una habilitat concreta i desa resultats locals per veure evolució sense necessitat de backend.</p><div class="fm-game-grid">${cards()}</div>`} function cards(){return games.map(g=>`<article class="fm-game-card fm-glass"><div class="fm-game-art">${g.image?`<img src="${g.image}" alt="" loading="lazy">`:`<span class="fm-game-emoji" aria-hidden="true">${g.emoji||'✦'}</span>`}</div><h3>${g.name}</h3><p class="fm-muted">${g.desc}</p><div class="fm-game-tags"><span>Objectiu: ${g.area}</span><span>${g.diff}</span><span>${g.duration}</span></div><p class="fm-muted"><strong>Què entrena?</strong> Precisió, autocontrol i resposta tàctil ràpida adaptada a tauleta.</p><button class="fm-btn" data-fm="play:${g.id}">Jugar</button></article>`).join('')}
function resultsView(){const rs=read(); $('.fm-view').innerHTML=`<h1 class="fm-section-title">Resultats</h1>${!rs.length?`<div class="fm-empty fm-glass">Encara no hi ha partides registrades. Comença un entrenament per veure la teva evolució.</div>`:`<div class="fm-stats">${stat('Total partides',rs.length)+stat('Millor global',bestGlobal())+stat('Millor joc',rs.sort((a,b)=>(b.score||0)-(a.score||0))[0]?.gameName||'—')+stat('Precisió mitjana',getFocusMindAverageAccuracy()+'%')+stat('Àrea forta',getFocusMindBestArea())+stat('Àrea a millorar',getFocusMindWeakestArea())}</div><div class="fm-badges">${badges().map(b=>`<div class="fm-badge">🏅 ${b}</div>`).join('')}</div><table class="fm-table"><thead><tr><th>Joc</th><th>Punts</th><th>Precisió</th><th>Data</th></tr></thead><tbody>${rs.slice(0,10).map(r=>`<tr><td>${r.gameName}</td><td>${r.score}</td><td>${r.accuracy}%</td><td>${new Date(r.date).toLocaleDateString('ca')}</td></tr>`).join('')}</tbody></table>`}`}
function badges(){const rs=read(), out=[]; if(rs.length)out.push('Primera partida'); if(rs.length>=5)out.push('5 partides jugades'); if(rs.some(r=>r.accuracy>=90))out.push('90% de precisió'); if(rs.some(r=>r.score>=1000))out.push('1000 punts'); if(rs.some(r=>r.cognitiveArea==='Memòria'&&r.score>700))out.push('Mestre de la memòria'); if(rs.some(r=>r.cognitiveArea==='Atenció'&&r.accuracy>80))out.push('Atenció activa'); return out.length?out:['Juga per desbloquejar badges']}
function header(g,s){return`<div class="fm-game-head fm-glass"><div><h1 class="fm-section-title">${g.name}</h1><p class="fm-muted">${g.desc}</p></div><div class="fm-hud"><span>Ronda ${s.round}</span><span>${s.score} punts</span><span>✓ ${s.correct}</span><span>✕ ${s.wrong}</span><span>${acc(s)}%</span><button class="fm-btn secondary" data-fm="jocs">Tornar als jocs</button><button class="fm-btn secondary" data-restart>Reiniciar</button><button class="fm-btn secondary" type="button">Pausa</button></div></div>`}
function acc(s){let t=s.correct+s.wrong;return t?Math.round(s.correct*100/t):100} function finish(g,s){let rt=avg(s.rts||[0]);let prev=getFocusMindBestScore(g.name);saveFocusMindResult({gameName:g.name,cognitiveArea:g.area,score:Math.max(0,s.score),correct:s.correct,wrong:s.wrong,accuracy:acc(s),averageReactionTime:rt});let msg=acc(s)>90?'Molt bon control i precisió.':acc(s)>=70?'Bon resultat. Pots millorar encara més amb pràctica.':'Cal reduir la velocitat i prioritzar la precisió.';document.body.insertAdjacentHTML('beforeend',`<div class="fm-modal"><div class="fm-modal-card fm-glass"><h2>Resultat final</h2><p class="fm-lead">${msg}</p><div class="fm-stats">${stat('Puntuació',s.score)+stat('Encerts',s.correct)+stat('Errors',s.wrong)+stat('Precisió',acc(s)+'%')+stat('Temps mitjà',rt+' ms')+stat('Millor anterior',prev)}</div><button class="fm-btn" data-repeat>Repetir partida</button> <button class="fm-btn secondary" data-back>Tornar als jocs</button></div></div>`);$('.fm-modal').onclick=e=>{if(e.target.closest('[data-repeat]')){$('.fm-modal').remove();startGame(g.id)} if(e.target.closest('[data-back]')){$('.fm-modal').remove();nav('/focusmind/jocs')}}}
function startGame(id){const g=games.find(x=>x.id===id)||games[0], s={round:1,score:0,correct:0,wrong:0,rts:[],start:Date.now()}; const v=$('.fm-view'); function paint(body){v.innerHTML=`<section class="fm-game-stage">${header(g,s)}<div class="fm-play fm-glass">${body}</div></section>`; $('[data-restart]')?.addEventListener('click',()=>startGame(id));}
if(id==='sequencia')return sequence(g,s,paint); if(id==='diferent')return different(g,s,paint); if(id==='color-paraula')return stroop(g,s,paint); if(id==='memoria-posicio')return position(g,s,paint); if(id==='ordre-creixent')return order(g,s,paint); return rule(g,s,paint)}
function sequence(g,s,paint){let seq=[],input=[],showing=true; next(); function next(){let n=s.round>=5?9:4;seq.push(Math.floor(Math.random()*n));input=[];showing=true;paint(`<div class="fm-grid" style="grid-template-columns:repeat(${Math.sqrt(n)},1fr)">${Array.from({length:n},(_,i)=>`<button class="fm-cell" data-i="${i}"></button>`).join('')}</div><p class="fm-muted">Observa la seqüència...</p>`);let k=0,t=setInterval(()=>{$$('.fm-cell').forEach(c=>c.classList.remove('on')); if(k>=seq.length){clearInterval(t);showing=false;$('.fm-muted').textContent='Ara repeteix el patró.';return} $(`.fm-cell[data-i="${seq[k++]}"]`).classList.add('on')},Math.max(420,900-s.round*45))} $('.fm-view').onclick=e=>{let c=e.target.closest('.fm-cell'); if(!c||showing)return; input.push(+c.dataset.i); c.classList.add('pick'); setTimeout(()=>c.classList.remove('pick'),180); if(input[input.length-1]!==seq[input.length-1]){s.wrong++;s.score-=40;return finish(g,s)} if(input.length===seq.length){s.correct++;s.score+=100+Math.max(0,80-(Date.now()-s.start)/1000|0);s.round++; if(s.round>12)return finish(g,s); setTimeout(next,450)}}}
function different(g,s,paint){const pairs=[['O','0'],['X','×'],['B','8'],['S','5'],['l','I'],['●','◐'],['C','G'],['Z','2']]; next(); function next(){if(s.round>10)return finish(g,s);let size=s.round<4?4:s.round<7?5:s.round<9?6:7,p=pairs[Math.floor(Math.random()*pairs.length)],odd=Math.floor(Math.random()*size*size),st=Date.now();paint(`<div class="fm-timer"><i style="width:100%"></i></div><div class="fm-grid" style="grid-template-columns:repeat(${size},1fr)">${Array.from({length:size*size},(_,i)=>`<button class="fm-cell" data-ok="${i===odd}">${i===odd?p[1]:p[0]}</button>`).join('')}</div>`);let left=100,iv=setInterval(()=>{left-=4;$('.fm-timer i').style.width=left+'%';if(left<=0){clearInterval(iv);s.wrong++;s.round++;next()}},160);$('.fm-grid').onclick=e=>{let b=e.target.closest('.fm-cell');if(!b)return;clearInterval(iv); if(b.dataset.ok==='true'){s.correct++;s.score+=100+Math.max(0,80-(Date.now()-st)/25|0);s.rts.push(Date.now()-st)}else{s.wrong++;s.score-=50}s.round++;next()}}}
function stroop(g,s,paint){const cs=[['VERMELL','#ef4444'],['BLAU','#3b82f6'],['VERD','#22c55e'],['GROC','#eab308'],['MORAT','#a855f7']];let end=Date.now()+30000; next(); function next(){if(Date.now()>end)return finish(g,s);let word=cs[Math.random()*5|0], col=cs[Math.random()*5|0],st=Date.now();paint(`<div class="fm-timer"><i style="width:${(end-Date.now())/300}%"></i></div><div class="fm-word" style="color:${col[1]}">${word[0]}</div><div class="fm-answer-grid">${cs.map(c=>`<button class="fm-btn secondary" data-c="${c[0]}">${c[0]}</button>`).join('')}</div>`);$('.fm-answer-grid').onclick=e=>{let b=e.target.closest('button');if(!b)return; if(b.dataset.c===col[0]){s.correct++;s.score+=80;s.rts.push(Date.now()-st)}else{s.wrong++;s.score-=40}s.round++;next()}}}
function position(g,s,paint){let selected=new Set(), pts=[]; next(); function next(){if(s.round>8)return finish(g,s);let size=s.round>=8?6:s.round>=5?5:4,count=s.round>=5?5:s.round>=3?4:3;pts=[];while(pts.length<count){let x=Math.random()*size*size|0;if(!pts.includes(x))pts.push(x)};paint(`<div class="fm-grid" style="grid-template-columns:repeat(${size},1fr)">${Array.from({length:size*size},(_,i)=>`<button class="fm-cell ${pts.includes(i)?'on':''}" data-i="${i}"></button>`).join('')}</div><button class="fm-btn" data-confirm disabled>Confirmar</button>`);setTimeout(()=>{$$('.fm-cell').forEach(c=>c.classList.remove('on'))},Math.max(900,2100-s.round*130));selected=new Set();$('.fm-grid').onclick=e=>{let c=e.target.closest('.fm-cell');if(!c)return;selected.has(c.dataset.i)?selected.delete(c.dataset.i):selected.add(c.dataset.i);c.classList.toggle('pick');$('[data-confirm]').disabled=selected.size!==pts.length};$('[data-confirm]').onclick=()=>{let ok=pts.every(p=>selected.has(String(p))); if(ok){s.correct+=pts.length;s.score+=120}else{s.wrong++;s.score-=60}s.round++;next()}}}
function order(g,s,paint){next(); function next(){if(s.round>8)return finish(g,s);let n=s.round<3?5:s.round<5?6:s.round<7?7:8, nums=Array.from({length:n},()=>Math.round((Math.random()*30- (s.round>4?10:0))*10)/10), sorted=[...nums].sort((a,b)=>a-b), idx=0,st=Date.now();paint(`<div class="fm-bubble-zone">${nums.map((x,i)=>`<button class="fm-bubble" style="left:${12+(i*73%n)}%;top:${18+((i*47)%66)}%" data-v="${x}">${x}</button>`).join('')}</div>`);$('.fm-bubble-zone').onclick=e=>{let b=e.target.closest('.fm-bubble');if(!b)return; if(+b.dataset.v===sorted[idx]){s.correct++;s.score+=50;b.remove();idx++; if(idx===sorted.length){s.score+=Math.max(0,160-(Date.now()-st)/40|0);s.rts.push((Date.now()-st)/n|0);s.round++;next()}}else{s.wrong++;s.score-=30;b.classList.add('danger')}}}}
function rule(g,s,paint){const shapes=['circle','square','triangle','diamond'], colors={blau:'#3b82f6',vermell:'#ef4444',verd:'#22c55e',groc:'#eab308',morat:'#a855f7'};let prev=null; next(); function getRule(){return [f=>f.shape==='circle',f=>f.color==='blau',f=>prev&&f.shape===prev.shape&&f.color===prev.color,f=>prev&&(f.shape!==prev.shape||f.color!==prev.color),f=>f.shape==='triangle'&&f.color==='vermell',f=>f.color!=='groc'][Math.floor((s.round-1)/4)%6]} function text(){return ['Respon SÍ si és un cercle.','Respon SÍ si és blau.','Respon SÍ si és igual a l’anterior.','Respon SÍ si és diferent de l’anterior.','Respon SÍ si és un triangle vermell.','Respon SÍ si NO és groc.'][Math.floor((s.round-1)/4)%6]} function next(){if(s.round>20)return finish(g,s);let fig={shape:shapes[Math.random()*4|0],color:Object.keys(colors)[Math.random()*5|0]}, ok=getRule()(fig),st=Date.now();paint(`<h2>${text()}</h2><div class="fm-rule-shape shape-${fig.shape}" style="--shape-color:${colors[fig.color]}"></div><div class="fm-yesno"><button class="fm-btn" data-a="yes">SÍ</button><button class="fm-btn danger" data-a="no">NO</button></div>`);$('.fm-yesno').onclick=e=>{let b=e.target.closest('button');if(!b)return; let yes=b.dataset.a==='yes'; if(yes===ok){s.correct++;s.score+=70;s.rts.push(Date.now()-st)}else{s.wrong++;s.score-=40} prev=fig;s.round++;next()}}}
window.initFocusMind=render; document.addEventListener('DOMContentLoaded',()=>{if(location.pathname.startsWith('/focusmind')){render(); if(typeof showView==='function') showView('focusmind');}});
})();
