const assert=require('node:assert/strict');const D=require('../daily-session-engine'),M=require('../daily-bank-metadata'),S=require('../daily-pedagogical-selector'),A=require('../daily-bank-functional-audit');global.addModules=()=>{};require('../math');require('../daily-activity-bank');
const deps={catalog:D.CATALOG,targets:S.TARGETS,metadata:M,activities:global.FocusDailyActivities,math:global.FocusMathGenerators},after=A.audit(deps);
assert.equal(after.rows.length,58);assert.equal(after.groups.A.length+after.groups.B.length+after.groups.C.length,58);assert.ok(after.groups.A.every(row=>row.missing.length&&['high','medium'].includes(row.priority)));assert.ok(after.groups.C.every(row=>row.missing.length===0||row.priority==='low'),'not-applicable procedures create no false high-priority alert');
const removed=new Set(['fact-family','operation-choice','fact-error']),before=A.audit({...deps,targets:S.TARGETS.filter(t=>!(['multiply-facts','divide-facts'].includes(t.procedure)&&removed.has(t.formatFamily)))});for(const procedure of ['multiply-facts','divide-facts']){const old=before.rows.find(r=>r.procedure===procedure),current=after.rows.find(r=>r.procedure===procedure);assert.equal(old.group,'A');assert.deepEqual(old.missing.sort(),['diagnosis','repair','return_after_stagnation','transfer']);assert.equal(current.group,'B');assert.deepEqual(current.missing,[]);assert.ok(current.representations.length>=4);}
for(const row of after.rows){if(row.capabilities.simplification!==A.AVAILABLE)continue;for(const target of S.TARGETS.filter(t=>t.skillId===row.skillId&&t.procedure===row.procedure&&t.level>1)){const skill=D.CATALOG[target.skillId],source=skill.generator.module==='daily'?global.FocusDailyActivities:global.FocusMathGenerators,q=source[skill.generator.activity||skill.generator.module](target.level-1,{...(skill.generator.options||{}),formatFamily:target.formatFamily,targetProcedure:target.procedure,simplified:true});assert.equal(D.describeFormat(q,q.type).procedure,target.procedure,`${target.procedure} remains the same when simplified`);}}
for(const row of after.rows.filter(r=>r.capabilities.transfer===A.AVAILABLE&&A.NEEDS.transfer.has(r.procedure)))assert.ok(row.representations.length>1||row.reasoningTypes.length>1,`${row.procedure} transfer is cognitive`);
for(const row of after.rows)for(const format of row.formats)if(format.diagnosticTags.length)assert.ok(['diagnose','select-operation','select-formula','evaluate-claim','evaluate-information','match-equivalent','complete','model','select-next-step','select-unit'].includes(format.reasoningType),`${format.formatId} only declares diagnostic tags for a discriminating response`);
const old=D.describeFormat('arith-facts-division','arith');assert.equal(old.procedure,'divide-facts');assert.equal(old.formatKey,'divide-facts|symbolic|execute|1|numeric','historical format identity remains stable');
const identities=new Set;for(const target of S.TARGETS.filter(t=>['multiply-facts','divide-facts'].includes(t.procedure))){const identity=[target.skillId,target.procedure,target.representation,target.formatFamily].join('|');assert.equal(identities.has(identity),false,`no duplicate cognitive target ${identity}`);identities.add(identity);}
console.log(`daily-bank-functional-audit: classified 58 procedures A=${after.groups.A.length}, B=${after.groups.B.length}, C=${after.groups.C.length}; high-priority fact bottlenecks resolved`);
