const assert=require('node:assert/strict');const D=require('../daily-session-engine'),S=require('../daily-pedagogical-selector');
const now='2026-10-03T10:00:00Z';
function session(items=[{id:'next',completed:false,phase:'focus'}]){return {id:'s',index:0,status:'in-progress',items,decisions:[]};}
function readyProfile(id='p'){const p=D.createProfile(id);for(const skill of Object.values(D.CATALOG)){const x=D.skillProgress(p,skill.id);x.status='mastered';x.estimatedLevel=Math.max(...skill.exerciseModel.levels);x.level=x.estimatedLevel;x.formatTaxonomyVersion=1;}return p;}
function addRaw(p,skillId,procedure,entries){const x=D.skillProgress(p,skillId);x.formatTaxonomyVersion=1;x.evidences=entries.map((e,i)=>({evidenceId:`${skillId}-${procedure}-${i}`,at:e.at||now,correct:e.correct!==false,outcome:e.correct===false?'incorrect':'correct',assistance:e.assistance||'none',procedureId:procedure,formatId:e.format||`${procedure}|${e.representation||'symbolic'}|execute|1|numeric`,format:{representation:e.representation||'symbolic'},difficulty:e.difficulty||x.estimatedLevel,exploratory:!!e.exploratory}));return x;}
// Pending routes pre-empt all new candidates, even when they were placed later.
{const p=readyProfile('verification'),s=session([{id:'new',phase:'focus'},{id:'verify',phase:'verification',skillId:'algebra.linear',procedureId:'solve-two-step',difficulty:2,formatFamily:'calculation',verifiesItemId:'old'}]);const r=S.selectNextActivity(p,s,{api:D,now});assert.equal(r.selected.reason,'mastery_confirmation');assert.equal(r.forcedItemId,'verify');S.ensureNextDecision(p,s,{api:D,now});assert.equal(s.items[0].id,'verify');}
{const p=readyProfile('prereq'),s=session([{id:'new',phase:'focus'},{id:'pre',phase:'prerequisite-check',skillId:'fractions.equivalence',difficulty:1,formatFamily:'missing-term',prerequisiteReviewId:'r'}]);assert.equal(S.selectNextActivity(p,s,{api:D,now}).selected.reason,'check_prerequisite');}
{const p=readyProfile('return'),s=session([{id:'new',phase:'focus'},{id:'return',phase:'return-to-procedure',skillId:'fractions.operations',difficulty:2,formatFamily:'symbolic',returnsFromPrerequisite:'r'}]);assert.equal(S.selectNextActivity(p,s,{api:D,now}).selected.reason,'return_after_prerequisite');}
{const p=readyProfile('resume'),s=session([{id:'started',phase:'focus',skillId:'data.interpretation',difficulty:1,formatFamily:'visual',presented:true,draftAnswer:'Dl'}]);assert.equal(S.selectNextActivity(p,s,{api:D,now}).selected.reason,'resume_activity');}
// One isolated error is not repair; two are.
{const p=readyProfile('one-error');addRaw(p,'fractions.operations','add-same-denominator',[{correct:false}]);const r=S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'fractions.operations',procedure:'add-same-denominator'}});assert.notEqual(r.selected.reason,'repair_after_error');addRaw(p,'fractions.operations','add-same-denominator',[{correct:false},{correct:false}]);assert.equal(S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'fractions.operations',procedure:'add-same-denominator'}}).selected.reason,'repair_after_error');}
// New, introduced and old procedures follow distinct routes.
{const p=readyProfile('new');addRaw(p,'numbers.decimals','compare-decimals',[]);const r=S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'numbers.decimals',procedure:'compare-decimals'}});assert.equal(r.selected.reason,'introduce_procedure');assert.equal(r.selected.activityType,'lesson_sequence');}
{const p=readyProfile('consolidate');addRaw(p,'numbers.decimals','compare-decimals',[{}]);const r=S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'numbers.decimals',procedure:'compare-decimals'}});assert.equal(r.selected.reason,'independent_consolidation');}
{const p=readyProfile('review');addRaw(p,'numbers.decimals','compare-decimals',Array.from({length:4},(_,i)=>({at:`2026-09-0${i+1}T10:00:00Z`,format:`f${i%2}`,representation:i%2?'number-line':'symbolic'})));const r=S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'numbers.decimals',procedure:'compare-decimals'}});assert.equal(r.selected.reason,'spaced_review');assert.match(r.selected.reasonDetails.join(' '),/days ago/);}
// False fluency changes representation without increasing level.
{const p=readyProfile('transfer'),x=addRaw(p,'algebra.linear','solve-two-step',Array.from({length:3},()=>({format:'same',representation:'symbolic',difficulty:2})));x.estimatedLevel=2;const s=session([{id:'done',completed:true,pedagogicalDecision:{procedure:'solve-two-step',formatFamily:'calculation'}},{id:'next'}]);s.index=1;const r=S.selectNextActivity(p,s,{api:D,now,scope:{skillId:'algebra.linear',procedure:'solve-two-step'}});assert.equal(r.selected.reason,'representation_transfer');assert.equal(r.selected.formatFamily,'complete');assert.equal(r.selected.estimatedLevel,2);}
// Stable autonomy permits a reversible probe; failing it does not lower the level.
{const p=readyProfile('probe'),x=addRaw(p,'calculation.muldiv','multiply-facts',[{format:'a',representation:'symbolic',difficulty:1},{format:'b',representation:'verbal',difficulty:1},{format:'c',representation:'symbolic',difficulty:1}]);x.estimatedLevel=1;x.levelRun={level:1,autonomous:0,errors:0,unknown:0,autonomousFormats:{},errorFormats:{}};const r=S.selectNextActivity(p,session(),{api:D,now,scope:{skillId:'calculation.muldiv',procedure:'multiply-facts'}});assert.equal(r.selected.reason,'difficulty_probe');assert.equal(r.selected.isExploration,true);D.recordEvidence(p,'calculation.muldiv',{evidenceId:'probe-fail',outcome:'incorrect',correct:false,assistance:'none',difficulty:2,formatId:'arith-two-digit-multiplication',procedureId:'written-multiplication',exploratory:true},now);assert.equal(D.skillProgress(p,'calculation.muldiv').estimatedLevel,1);assert.equal(D.skillProgress(p,'calculation.muldiv').levelRun.errors,0);}
// A recent equivalent transfer is not repeated without new diverse evidence.
{const p=readyProfile('transfer-cooldown'),x=addRaw(p,'algebra.linear','solve-two-step',Array.from({length:3},()=>({format:'same',representation:'symbolic',difficulty:2})));x.estimatedLevel=2;const s=session([{id:'transfer',completed:true,correct:true,assistance:'none',pedagogicalDecision:{skillId:'algebra.linear',procedure:'solve-two-step',formatFamily:'complete',cognitiveFormat:'solve-two-step|worked-step|targeted|2|generated-response',reason:'representation_transfer',decidedAt:'2026-10-03T09:00:00Z'}},{id:'next'}]);s.index=1;assert.notEqual(S.selectNextActivity(p,s,{api:D,now,scope:{skillId:'algebra.linear',procedure:'solve-two-step'}}).selected.reason,'representation_transfer');}
// A probe cannot repeat until intermediate autonomous evidence exists.
{const p=readyProfile('probe-cooldown'),x=addRaw(p,'calculation.muldiv','multiply-facts',[{format:'a',representation:'symbolic',at:'2026-10-02T08:00:00Z'},{format:'b',representation:'verbal',at:'2026-10-02T08:01:00Z'},{format:'c',representation:'symbolic',at:'2026-10-02T08:02:00Z'}]);x.estimatedLevel=1;const s=session([{id:'probe',completed:true,correct:true,assistance:'none',pedagogicalDecision:{skillId:'calculation.muldiv',procedure:'multiply-facts',reason:'difficulty_probe',probeKey:'calculation.muldiv:1->2',decidedAt:'2026-10-03T09:00:00Z'}},{id:'next'}]);s.index=1;assert.equal(S.selectNextActivity(p,s,{api:D,now,scope:{skillId:'calculation.muldiv',procedure:'multiply-facts'}}).selected.reason,'independent_consolidation');}
// Two unproductive repairs switch strategy instead of selecting a third repair.
{const p=readyProfile('repair-strategy');addRaw(p,'numbers.decimals','compare-decimals',[{correct:false},{correct:false}]);const repairDecision={skillId:'numbers.decimals',procedure:'compare-decimals',formatFamily:'compare',reason:'repair_after_error',activityType:'repair_practice'};const s=session([{id:'r1',completed:true,correct:false,assistance:'none',pedagogicalDecision:repairDecision},{id:'r2',completed:true,correct:true,assistance:'hint',pedagogicalDecision:repairDecision},{id:'next'}]);s.index=2;const r=S.selectNextActivity(p,s,{api:D,now,scope:{skillId:'numbers.decimals',procedure:'compare-decimals'}});assert.equal(r.selected.reason,'guided_practice');assert.equal(r.selected.activityType,'lesson_sequence');}
// Two introductions yield to an available consolidation candidate.
{const p=readyProfile('intro-guard');addRaw(p,'numbers.decimals','compare-decimals',[{}]);const intro={reason:'introduce_procedure'};const s=session([{id:'i1',completed:true,pedagogicalDecision:{...intro,skillId:'data.interpretation',procedure:'read-value'}},{id:'i2',completed:true,pedagogicalDecision:{...intro,skillId:'geometry.measure',procedure:'rectangle-area'}},{id:'next'}]);s.index=2;const r=S.selectNextActivity(p,s,{api:D,now});assert.notEqual(r.selected.reason,'introduce_procedure');assert.ok(r.discarded.some(d=>d.discardReason?.includes('consolidate before')));}
// Variety and coverage cannot defeat a strictly more urgent repair candidate.
{const p=readyProfile('urgent');addRaw(p,'fractions.operations','add-same-denominator',[{correct:false},{correct:false}]);const s=session([{id:'other',completed:true,pedagogicalDecision:{skillId:'data.interpretation',procedure:'read-value',formatFamily:'visual',reason:'coverage_balance'}},{id:'next'}]);s.index=1;const r=S.selectNextActivity(p,s,{api:D,now});assert.equal(r.selected.reason,'repair_after_error');assert.equal(r.preference.rule,'higher_pedagogical_priority');assert.ok(r.preference.priorityDifference>0);assert.ok(r.runnerUp);}
// The decided next item and its reason survive serialization and every decision uses a controlled reason.
{const p=D.createProfile('persist'),s=D.planSession(p,now);S.ensureNextDecision(p,s,{api:D,now});const restored=JSON.parse(JSON.stringify(s));assert.deepEqual(restored.items[0].pedagogicalDecision,s.items[0].pedagogicalDecision);assert.ok(S.REASONS.includes(restored.items[0].pedagogicalDecision.reason));assert.ok(restored.items[0].reasonDetails.length);}
{const a=D.createProfile('deterministic-a'),b=JSON.parse(JSON.stringify(a)),sa=session(),sb=JSON.parse(JSON.stringify(sa));assert.deepEqual(S.selectNextActivity(a,sa,{api:D,now}).selected,S.selectNextActivity(b,sb,{api:D,now}).selected,'equivalent state gives the same decision without random choice');}
console.log('daily-pedagogical-selector: priorities, repair, introduction, consolidation, review, transfer, probe and persistence passed');
