const assert=require('node:assert/strict');
const D=require('../daily-session-engine'),P=require('../daily-prerequisites');
function evidence(profile,n,outcome='incorrect',assistance='none'){D.recordEvidence(profile,'fractions.operations',{evidenceId:`e${n}`,outcome,correct:outcome==='correct',assistance,difficulty:2,formatId:'frac-arith-+',formatKey:'add-different-denominator|symbolic|execute|2|fraction',procedureId:'add-different-denominator'},`2026-01-0${n+1}T10:00:00Z`);}
function route(){return {id:'s',status:'in-progress',index:0,items:[{id:'done',skillId:'fractions.operations',formatFamily:'symbolic',completed:true},{id:'check',skillId:'fractions.operations'},{id:'after',skillId:'fractions.operations'}]};}
{const p=D.createProfile('one');evidence(p,0);assert.equal(P.eligible(p,'fractions.operations','add-different-denominator'),null,'one error is insufficient');}
{const p=D.createProfile('repeat');evidence(p,0);evidence(p,1);const s=route(),review=P.schedule(p,s,s.items[0],{procedure:'add-different-denominator'});assert.ok(review);assert.equal(s.items[1].phase,'prerequisite-check');assert.equal(s.items[1].skillId,'fractions.equivalence');s.index=1;Object.assign(s.items[1],{completed:true,correct:true,assistance:'none'});P.resolve(p,s,s.items[1]);assert.equal(s.items[2].phase,'return-to-procedure');assert.equal(s.items[2].skillId,'fractions.operations');}
{const p=D.createProfile('reinforce');evidence(p,0);evidence(p,1);const s=route();P.schedule(p,s,s.items[0],{procedure:'add-different-denominator'});s.index=1;Object.assign(s.items[1],{completed:true,correct:false,assistance:'hint'});const review=P.resolve(p,s,s.items[1]);assert.equal(review.result,'needs-reinforcement');assert.equal(s.items[2].phase,'prerequisite-reinforcement');assert.equal(s.items[2].skillId,'fractions.equivalence');const restored=JSON.parse(JSON.stringify({profile:p,session:s}));assert.equal(restored.profile.prerequisiteReviews[0].result,'needs-reinforcement');assert.equal(restored.session.items[2].phase,'prerequisite-reinforcement');assert.equal(D.skillProgress(p,'fractions.equivalence').status,'pending','assisted prerequisite work does not create mastery');}
{const legacy={skills:{},prerequisiteReviews:null,pendingPrerequisites:null};P.ensure(legacy);assert.deepEqual(legacy.prerequisiteReviews,[]);assert.deepEqual(legacy.pendingPrerequisites,{});}
console.log('daily-prerequisites: activation, return, reinforcement, assistance and migration passed');
