const assert=require('node:assert/strict');const D=require('../daily-session-engine'),M=require('../daily-bank-metadata'),S=require('../daily-pedagogical-selector'),Answer=require('../daily-answer');global.addModules=()=>{};require('../math.js');require('../daily-activity-bank.js');
function generate(t){const skill=D.CATALOG[t.skillId],source=skill.generator.module==='daily'?global.FocusDailyActivities:global.FocusMathGenerators,q=source[skill.generator.activity||skill.generator.module](t.level,{...(skill.generator.options||{}),formatFamily:t.formatFamily,targetProcedure:t.procedure});return M.enrich(q);}
const required=['skill','procedure','level','representation','reasoningType','stepCount','answerType','formatFamily','diagnosticTags','supportsSimplification','supportsTransfer'];
for(const target of S.TARGETS){for(let i=0;i<30;i++){const q=generate(target);for(const key of required)assert.notEqual(q[key],undefined,`${q.formatId}: ${key}`);assert.notEqual(q.procedure,'unspecified',`${target.procedure}/${target.formatFamily} has a procedure`);assert.ok(q.text&&q.answer!==undefined,`${q.formatId} is self-contained`);if(q.choices){assert.equal(new Set(q.choices.map(String)).size,q.choices.length,`${q.formatId} has unique choices`);assert.ok(q.choices.map(String).includes(String(q.answer)),`${q.formatId} contains its answer`);}}}
const fractionProcedures=['add-same-denominator','subtract-same-denominator','add-different-denominator','subtract-different-denominator','multiply-fractions','divide-fractions'];for(const procedure of fractionProcedures){const targets=S.TARGETS.filter(t=>t.procedure===procedure);assert.deepEqual(new Set(targets.map(t=>t.representation)),new Set(['symbolic','worked-step','worked-error','verbal-context']),`${procedure} has direct, step, diagnostic and contextual representations`);for(const t of targets)for(let i=0;i<80;i++){const q=generate(t);assert.equal(q.procedure,procedure);assert.equal(Answer.validate(q.answer,q).correct,true);}}

for(const target of S.TARGETS.filter(t=>t.level>1)){const normal=generate(target);if(!normal.supportsSimplification)continue;const simpler={...target,level:target.level-1},q=generate(simpler);assert.equal(q.procedure,target.procedure,`${target.procedure} simplification keeps the procedure`);assert.ok(q.level<target.level||q.difficulty<target.level,`${target.procedure} lowers declared load`);}
const diagnostic=S.TARGETS.map(generate).filter(q=>q.diagnosticTags.length);assert.ok(diagnostic.some(q=>q.diagnosticTags.includes('distributive-property')));assert.ok(diagnostic.some(q=>q.diagnosticTags.includes('correlation-not-causation')));assert.ok(diagnostic.some(q=>q.diagnosticTags.includes('conversion-direction')));assert.ok(diagnostic.some(q=>q.diagnosticTags.includes('denominator-rule')));
const transferByProcedure={};for(const q of S.TARGETS.map(generate)){(transferByProcedure[q.procedure]||(transferByProcedure[q.procedure]=new Set())).add(q.representation);}for(const procedure of fractionProcedures)assert.ok(transferByProcedure[procedure].size>=4);
for(let i=0;i<100;i++){const q=global.FocusMathGenerators.fractions(1,{sub:'arith',dailyAdaptive:true,targetProcedure:'add-different-denominator',formatFamily:'symbolic',simplified:true});assert.equal(D.describeFormat(q,q.type).procedure,'add-different-denominator');assert.equal(q.denominatorsDifferent,true);}
console.log(`daily-bank-expansion: ${S.TARGETS.length} selectable cognitive formats validated with metadata, diagnostics, simplification and transfer`);
