const assert=require('node:assert/strict'),L=require('../daily-lessons');
const required=['decimal-place-value','decimal-compare','decimal-order','decimal-representations','estimate-magnitude','estimate-result','data-compare','data-trend','data-conclusion','equation-parentheses','multistep-strategy'];
for(const id of required){const x=L.lessons[id];assert.ok(x?.objective&&x.explanation&&x.visual&&x.steps.length>=3&&x.check?.text&&x.guided?.text,id);assert.ok(x.check.choices.includes(x.check.answer));assert.ok(x.guided.choices.includes(x.guided.answer));}
const cases=[
 [{formatId:'decimal-compare'},'numbers.decimals','decimal-compare'],[{formatId:'decimal-order'},'numbers.decimals','decimal-order'],[{formatId:'decimal-fraction-percent'},'numbers.decimals','decimal-representations'],[{formatId:'units-estimate'},'measurement.units','estimate-magnitude'],[{formatId:'geometry-estimate'},'geometry.measure','estimate-result'],[{formatId:'graph-trend'},'data.interpretation','data-trend'],[{formatId:'graph-compare'},'data.interpretation','data-compare'],[{formatId:'graph-read-justify'},'data.interpretation','data-conclusion'],[{formatId:'equation-parentheses'},'algebra.linear','equation-parentheses'],[{formatId:'units-multistep'},'measurement.units','multistep-strategy']];
for(const [exercise,skill,lesson] of cases)assert.equal(L.procedureFor(exercise,skill),lesson);
assert.notEqual(L.procedureFor({formatId:'graph-trend'},'data.interpretation'),'graph-reading');assert.notEqual(L.procedureFor({formatId:'equation-parentheses'},'algebra.linear'),'linear-equation');
const decimalProfile={skills:{'numbers.decimals':{evidences:[{correct:true,assistance:'none',rawFormatId:'decimal-compare'}]}},lessons:{}};assert.equal(L.shouldIntroduce(decimalProfile,'numbers.decimals','decimal-compare'),false);assert.equal(L.shouldIntroduce(decimalProfile,'numbers.decimals','decimal-order'),true,'evidence from a neighboring decimal procedure must not suppress its lesson');
const dataProfile={skills:{'data.interpretation':{evidences:[{correct:true,assistance:'none',rawFormatId:'graph-read-value'}]}},lessons:{}};assert.equal(L.shouldIntroduce(dataProfile,'data.interpretation','data-trend'),true,'graph reading does not suppress trend teaching');
console.log('daily-lesson-coverage: new lessons are complete and procedure-specific');
