const assert=require('node:assert/strict');
const D=require('../daily-session-engine');
const T=require('../daily-stagnation');
const S=require('../daily-pedagogical-selector');
const now='2026-10-10T09:00:00Z';
const route=()=>({id:'s',index:0,items:[{id:'next'}]});
function add(p,skill,procedure,rows){const x=D.skillProgress(p,skill);rows.forEach((r,i)=>x.evidences.push({evidenceId:`e-${i}-${r.at}`,at:r.at,procedureId:procedure,correct:r.correct??false,outcome:r.correct?'correct':'incorrect',assistance:r.assistance||'none',difficulty:r.difficulty||1,formatId:r.format||'symbolic',format:{representation:r.representation||'symbolic'},exploratory:!!r.exploratory}));return x;}
function repairs(p,skill,procedure,count=2){p.sessions=[{id:'history',decisions:Array.from({length:count},(_,i)=>({skillId:skill,procedure,reason:'repair_after_error',activityType:'repair_practice',decidedAt:`2026-10-0${6+i}T09:00:00Z`,correct:false,assistance:'none'}))}];}
const errors=[1,3,5,7].map((d,i)=>({at:`2026-10-0${d}T09:00:00Z`,correct:false,format:i%2?'context':'symbolic'}));
// One error, one bad day, a failed probe and even errors without attempted intervention are not stagnation.
{const p=D.createProfile('isolated');add(p,'algebra.linear','solve-two-step',[{at:'2026-10-09T09:00:00Z',correct:false}]);assert.equal(T.inspect(p,route(),'algebra.linear','solve-two-step',now).state,null);}
{const p=D.createProfile('bad-day');add(p,'algebra.linear','solve-two-step',errors.map(e=>({...e,at:'2026-10-09T09:00:00Z'})));assert.equal(T.inspect(p,route(),'algebra.linear','solve-two-step',now).state,null);}
{const p=D.createProfile('probe');add(p,'algebra.linear','solve-two-step',errors.map(e=>({...e,exploratory:true})));repairs(p,'algebra.linear','solve-two-step');assert.equal(T.inspect(p,route(),'algebra.linear','solve-two-step',now).state,null);}
{const p=D.createProfile('unpatterned');add(p,'algebra.linear','solve-two-step',errors);assert.equal(T.inspect(p,route(),'algebra.linear','solve-two-step',now).state,null);}
// Sustained assisted dependence is classified without pretending it is conceptual.
{const p=D.createProfile('help');add(p,'algebra.linear','solve-two-step',[1,3,5,7].map(d=>({at:`2026-10-0${d}T09:00:00Z`,correct:true,assistance:'hint'})));const out=T.inspect(p,route(),'algebra.linear','solve-two-step',now);assert.equal(out.state.reason,'help_dependence');assert.equal(T.nextStrategy(out.state,now).strategy,'fade_help');}
// A failed compatible prerequisite check supports a conceptual diagnosis and prerequisite strategy.
{const p=D.createProfile('concept');add(p,'fractions.operations','divide-fractions',errors);repairs(p,'fractions.operations','divide-fractions');p.prerequisiteReviews=[{originalSkillId:'fractions.operations',originalProcedureId:'divide-fractions',result:'needs-reinforcement'}];const out=T.inspect(p,route(),'fractions.operations','divide-fractions',now);assert.equal(out.state.reason,'conceptual');assert.equal(T.nextStrategy(out.state,now).strategy,'prerequisite');}
{const p=D.createProfile('unrelated-prerequisite');add(p,'fractions.operations','divide-fractions',errors);repairs(p,'fractions.operations','divide-fractions');p.prerequisiteReviews=[{originalSkillId:'algebra.linear',originalProcedureId:'equation-parentheses',result:'needs-reinforcement'}];const out=T.inspect(p,route(),'fractions.operations','divide-fractions',now);assert.notEqual(out.state.reason,'conceptual','an unrelated prerequisite cannot create a conceptual diagnosis');assert.notEqual(T.nextStrategy(out.state,now).strategy,'prerequisite');}
// Symbolic fluency that fails in context is false fluency.
{const p=D.createProfile('false');const rows=[1,2,3].map(d=>({at:`2026-10-0${d}T09:00:00Z`,correct:true,format:'sym',representation:'symbolic'})).concat([5,7].map(d=>({at:`2026-10-0${d}T09:00:00Z`,correct:false,format:'ctx',representation:'verbal-context'})));add(p,'algebra.linear','solve-two-step',rows);repairs(p,'algebra.linear','solve-two-step');const out=T.inspect(p,route(),'algebra.linear','solve-two-step',now);assert.equal(out.state.reason,'false_fluency');assert.equal(T.nextStrategy(out.state,now).strategy,'change_representation');}
// Success at low load followed by repeated high-load errors is overload and simplifies.
{const p=D.createProfile('overload');add(p,'algebra.linear','solve-two-step',[{at:'2026-10-01T09:00:00Z',correct:true,difficulty:1},{at:'2026-10-03T09:00:00Z',correct:false,difficulty:3},{at:'2026-10-05T09:00:00Z',correct:false,difficulty:3},{at:'2026-10-07T09:00:00Z',correct:false,difficulty:3}]);repairs(p,'algebra.linear','solve-two-step');const out=T.inspect(p,route(),'algebra.linear','solve-two-step',now);assert.equal(out.state.reason,'difficulty_overload');assert.equal(T.nextStrategy(out.state,now).strategy,'simplify');}
// Strategy rotation, pause, return, persistence and resolution only from autonomous evidence.
{const p=D.createProfile('rotate');add(p,'algebra.linear','solve-two-step',errors);repairs(p,'algebra.linear','solve-two-step');let out=T.inspect(p,route(),'algebra.linear','solve-two-step',now),state=out.state;assert.equal(state.reason,'procedural');const first=T.nextStrategy(state,now);T.recordStrategy(p,'algebra.linear','solve-two-step',first.strategy,'first',now);const second=T.nextStrategy(state,now);assert.notEqual(second.strategy,first.strategy,'the same strategy is not selected indefinitely');for(const strategy of T.STRATEGY_ORDER.procedural.slice(1))T.recordStrategy(p,'algebra.linear','solve-two-step',strategy,strategy,now);assert.equal(T.nextStrategy(state,now).strategy,'temporary_pause');T.recordStrategy(p,'algebra.linear','solve-two-step','temporary_pause','pause',now);assert.equal(T.nextStrategy(state,'2026-10-11T09:00:00Z').strategy,'temporary_pause');assert.equal(T.nextStrategy(state,'2026-10-13T09:00:00Z').strategy,'return_after_pause');const restored=JSON.parse(JSON.stringify(p));assert.equal(restored.stagnationStates['algebra.linear:solve-two-step'].reason,'procedural');add(p,'algebra.linear','solve-two-step',[{at:'2026-10-11T09:00:00Z',correct:true,assistance:'hint',format:'new'}]);out=T.inspect(p,route(),'algebra.linear','solve-two-step','2026-10-11T10:00:00Z');assert.equal(out.state.status,'active','assisted success cannot resolve stagnation');add(p,'algebra.linear','solve-two-step',[{at:'2026-10-12T09:00:00Z',correct:true,format:'new-a'}]);out=T.inspect(p,route(),'algebra.linear','solve-two-step','2026-10-12T10:00:00Z');assert.equal(out.state.status,'still_learning');add(p,'algebra.linear','solve-two-step',[{at:'2026-10-14T09:00:00Z',correct:true,format:'new-b'}]);out=T.inspect(p,route(),'algebra.linear','solve-two-step','2026-10-14T10:00:00Z');assert.equal(out.state.status,'stagnation_resolved');assert.equal(T.metrics(p).resolved,1);}
// The existing selector consumes the diagnosis as a subreason rather than creating a second selector.
{const p=D.createProfile('selector');for(const skill of Object.values(D.CATALOG)){const x=D.skillProgress(p,skill.id);x.status='mastered';x.estimatedLevel=Math.max(...skill.exerciseModel.levels);}add(p,'numbers.decimals','compare-decimals',[1,3,5,7].map(d=>({at:`2026-10-0${d}T09:00:00Z`,correct:true,assistance:'hint'})));const result=S.selectNextActivity(p,route(),{api:D,stagnationApi:T,now,scope:{skillId:'numbers.decimals',procedure:'compare-decimals'}});assert.equal(result.selected.stagnation.type,'help_dependence');assert.equal(result.selected.stagnation.strategy,'fade_help');assert.equal(result.selected.reason,'repair_after_error');}
assert.deepEqual(T.TYPES,['procedural','conceptual','help_dependence','false_fluency','difficulty_overload','undetermined']);
console.log('daily-stagnation: detection, diagnosis, strategy rotation, pause, resolution and selector integration passed');
